@@ -0,0 +1,44 @@
name: generate animation

 # Executa automaticamente todos os dias à meia-noite UTC
  schedule:
    - cron: "0 0 * * *"
  
  # Permite rodar manualmente o workflow
  workflow_dispatch:
  
  # Roda toda vez que há um push na branch principal
  push:
    branches:
      - main  # Altere para 'master' se sua branch principal for essa

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Gera a animação da cobrinha com os commits
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # Publica os arquivos gerados na branch 'output'
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
